[package]
name = "image-compressor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
lodepng = "3.7.2"
flate2 = "1.0.25"
imagequant = "4.1.1"